Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = plt.subplots(1, 1, figsize=(10, 5))
ax = plot_credible_intervals(a, b, ax)
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[14], line 2[0m
[1;32m      1[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots([38;5;241m1[39m, [38;5;241m1[39m, figsize[38;5;241m=[39m([38;5;241m10[39m, [38;5;241m5[39m))
[0;32m----> 2[0m ax [38;5;241m=[39m [43mplot_credible_intervals[49m[43m([49m[43ma[49m[43m,[49m[43m [49m[43mb[49m[43m,[49m[43m [49m[43max[49m[43m)[49m
[1;32m      3[0m plt[38;5;241m.[39mshow()

Cell [0;32mIn[13], line 59[0m, in [0;36mplot_credible_intervals[0;34m(a, b, ax)[0m
[1;32m     57[0m ax[38;5;241m.[39mlegend(loc[38;5;241m=[39m[38;5;124m'[39m[38;5;124mbest[39m[38;5;124m'[39m)
[1;32m     58[0m ax[38;5;241m.[39mset_yticks(np[38;5;241m.[39marange([38;5;241m-[39mtop_n, top_n [38;5;241m+[39m [38;5;241m1[39m))
[0;32m---> 59[0m [43max[49m[38;5;241;43m.[39;49m[43mset_yticklabels[49m[43m([49m[43m[[49m[43mname[49m[43m[[49m[38;5;241;43m1[39;49m[43m][49m[43m [49m[38;5;28;43;01mfor[39;49;00m[43m [49m[43mname[49m[43m [49m[38;5;129;43;01min[39;49;00m[43m [49m[43mmovie_names[49m[43m][49m[43m)[49m
[1;32m     60[0m [38;5;28;01mreturn[39;00m ax

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/matplotlib/axes/_base.py:74[0m, in [0;36m_axis_method_wrapper.__set_name__.<locals>.wrapper[0;34m(self, *args, **kwargs)[0m
[1;32m     73[0m [38;5;28;01mdef[39;00m [38;5;21mwrapper[39m([38;5;28mself[39m, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m---> 74[0m     [38;5;28;01mreturn[39;00m [43mget_method[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/matplotlib/_api/deprecation.py:297[0m, in [0;36mrename_parameter.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    292[0m     warn_deprecated(
[1;32m    293[0m         since, message[38;5;241m=[39m[38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe [39m[38;5;132;01m{[39;00mold[38;5;132;01m!r}[39;00m[38;5;124m parameter of [39m[38;5;132;01m{[39;00mfunc[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m() [39m[38;5;124m"[39m
[1;32m    294[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mhas been renamed [39m[38;5;132;01m{[39;00mnew[38;5;132;01m!r}[39;00m[38;5;124m since Matplotlib [39m[38;5;132;01m{[39;00msince[38;5;132;01m}[39;00m[38;5;124m; support [39m[38;5;124m"[39m
[1;32m    295[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mfor the old name will be dropped %(removal)s.[39m[38;5;124m"[39m)
[1;32m    296[0m     kwargs[new] [38;5;241m=[39m kwargs[38;5;241m.[39mpop(old)
[0;32m--> 297[0m [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/matplotlib/axis.py:1969[0m, in [0;36mAxis.set_ticklabels[0;34m(self, labels, minor, fontdict, **kwargs)[0m
[1;32m   1965[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(locator, mticker[38;5;241m.[39mFixedLocator):
[1;32m   1966[0m     [38;5;66;03m# Passing [] as a list of labels is often used as a way to[39;00m
[1;32m   1967[0m     [38;5;66;03m# remove all tick labels, so only error for > 0 labels[39;00m
[1;32m   1968[0m     [38;5;28;01mif[39;00m [38;5;28mlen[39m(locator[38;5;241m.[39mlocs) [38;5;241m!=[39m [38;5;28mlen[39m(labels) [38;5;129;01mand[39;00m [38;5;28mlen[39m(labels) [38;5;241m!=[39m [38;5;241m0[39m:
[0;32m-> 1969[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m   1970[0m             [38;5;124m"[39m[38;5;124mThe number of FixedLocator locations[39m[38;5;124m"[39m
[1;32m   1971[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124m ([39m[38;5;132;01m{[39;00m[38;5;28mlen[39m(locator[38;5;241m.[39mlocs)[38;5;132;01m}[39;00m[38;5;124m), usually from a call to[39m[38;5;124m"[39m
[1;32m   1972[0m             [38;5;124m"[39m[38;5;124m set_ticks, does not match[39m[38;5;124m"[39m
[1;32m   1973[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124m the number of labels ([39m[38;5;132;01m{[39;00m[38;5;28mlen[39m(labels)[38;5;132;01m}[39;00m[38;5;124m).[39m[38;5;124m"[39m)
[1;32m   1974[0m     tickd [38;5;241m=[39m {loc: lab [38;5;28;01mfor[39;00m loc, lab [38;5;129;01min[39;00m [38;5;28mzip[39m(locator[38;5;241m.[39mlocs, labels)}
[1;32m   1975[0m     func [38;5;241m=[39m functools[38;5;241m.[39mpartial([38;5;28mself[39m[38;5;241m.[39m_format_with_dict, tickd)

[0;31mValueError[0m: The number of FixedLocator locations (21), usually from a call to set_ticks, does not match the number of labels (20).

